name: Artifacts upload 

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dummy file
        run: |
          mkdir -p ./data
          echo hello > ./data/file.txt

      - name: Upload to build artifacts
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: output_file
          path: ./data/*

      - name: Print link to file
        run: echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload.outputs.artifact-id }}"
