name: Workflow that calls a reusable workflow
on:
  workflow_dispatch:   
      

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Echo hello 1
        run: echo Hello 1    
      
      - name: Echo finished
        run: echo Finished  

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      caller-name: "GitHub actor"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Echo hello 2
        run: echo Hello 2      
      
      - name: Echo finished
        run: echo Finished  
