name: Test creating containers
on:
  workflow_dispatch

jobs:
  demo-container-port-mapping:
    runs-on: ubuntu-latest
        
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        ports:
          # Opens tcp port 5432 on the host and service container
          - 5432:5432
    steps:
      - name: Test Postgres connection
        run: nc -v 127.0.0.1 5432       
       
  demo-container-job:
    runs-on: ubuntu-latest

    # Docker Hub image that `demo-container-job` executes in
    container: subfuzion/netcat
        
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres

    steps:
      - name: Test Postgres connection
        run: nc -v postgres 5432
  
