name: Test job failures

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application
        uses: actions/checkout@v2
     
      - name: Before failure
        run: echo "before"
        
      - name: Other fail
        run: | 
          exit 1        
       
      - name: This will fail
        id: failing_step
        run: | 
          exit 1

      - name: This should execute if all success or if 'This will fail' fails
        if: success() || steps.failing_step.outcome == 'failure'
        run: echo "this should be seen"
    
      - name: This should not execute
        run: echo "this should not be seen"
