name: Test job failures

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application
        uses: actions/checkout@v2
     
      - name: Before failure
        run: echo "before"
       
      - name: This will fail
        run: | 
          exit 1
          echo ::set-output name=some_step_exit_code::$?

      - name: This should execute if all success or if 'This will fail' fails
        if: ${{ success() || steps.build.outputs.some_step_exit_code != 0 }}
        run: echo "this should be seen"
    
      - name: This should not execute
        run: echo "this should not be seen"
